- name: install and start mysql
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: install mysql
    ansible.builtin.package:
      name: mysql
      state: absent

  - name: start mysql
    ansible.builtin.service:
      name: mysql
      state: started
      enabled: yes