- name: conditions
  hosts: local
  connection: local
  vars:
    number: 35
  tasks:
  - name: check number is even or odd
    ansible.builtin.debug:
      msg: 
      {% if number is divisible by 2 %}
        "Given number {{ number }} is even number"
      {% else %}
        "Given number {{ number }} is odd number"
      {% endif %}